[package]
name = "neqo-transport"
version = "0.6.8"
authors = ["EKR <ekr@rtfm.com>", "Andy Grover <agrover@mozilla.com>"]
edition = "2018"
rust-version = "1.70.0"
license = "MIT OR Apache-2.0"

[dependencies]
neqo-crypto = { path = "../neqo-crypto" }
neqo-common = { path = "../neqo-common" }
lazy_static = "1.3.0"
log = {version = "0.4.0", features = ["max_level_off"]}
smallvec = "1.0.0"
qlog = "0.9.0"
indexmap = "1.0"

[dev-dependencies]
test-fixture = { path = "../test-fixture" }
criterion = { version = "0.4", features = ["html_reports"] }

[features]
deny-warnings = []
fuzzing = ["neqo-crypto/fuzzing"]

[[bench]]
name = "range_tracker"
harness = false
